/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BoxChat;

import java.awt.CardLayout;
import java.awt.Color;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JButton;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dell
 */
public class Server extends javax.swing.JFrame {

    /**
     * Creates new form Bai2Client
     */
    ServerSocket serverSocket;
    Socket socket;
    ChatMesageSocket messSocket;
    
    public Server() {
        initComponents();
        connect("Client",edChatBox1,9999).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlClient1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblClient1 = new javax.swing.JLabel();
        statusClient1 = new javax.swing.JLabel();
        pnlClient2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblClient2 = new javax.swing.JLabel();
        statusClient4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSent = new javax.swing.JButton();
        txtMess = new javax.swing.JTextField();
        pnlCard = new javax.swing.JPanel();
        spClient1 = new javax.swing.JScrollPane();
        edChatBox1 = new javax.swing.JEditorPane();
        spClient2 = new javax.swing.JScrollPane();
        edChatBox2 = new javax.swing.JEditorPane();
        lblNameClient = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 255));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlClient1.setBackground(new java.awt.Color(255, 102, 102));
        pnlClient1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlClient1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlClient1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlClient1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlClient1MouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesBoxChat/icons8_administrator_male_73px_1.png"))); // NOI18N

        lblClient1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClient1.setForeground(new java.awt.Color(51, 51, 51));
        lblClient1.setText("Client 1");

        statusClient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesBoxChat/iconOnline.png"))); // NOI18N

        javax.swing.GroupLayout pnlClient1Layout = new javax.swing.GroupLayout(pnlClient1);
        pnlClient1.setLayout(pnlClient1Layout);
        pnlClient1Layout.setHorizontalGroup(
            pnlClient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlClient1Layout.setVerticalGroup(
            pnlClient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClient1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlClient1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlClient1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlClient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClient1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlClient2.setBackground(new java.awt.Color(255, 102, 102));
        pnlClient2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlClient2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlClient2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlClient2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlClient2MouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesBoxChat/icons8_security_specialist_male_73px.png"))); // NOI18N

        lblClient2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblClient2.setForeground(new java.awt.Color(51, 51, 51));
        lblClient2.setText("Client 2");

        statusClient4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesBoxChat/iconOffline.png"))); // NOI18N

        javax.swing.GroupLayout pnlClient2Layout = new javax.swing.GroupLayout(pnlClient2);
        pnlClient2.setLayout(pnlClient2Layout);
        pnlClient2Layout.setHorizontalGroup(
            pnlClient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClient2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblClient2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(statusClient4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClient2Layout.setVerticalGroup(
            pnlClient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClient2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlClient2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlClient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusClient4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClient2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlClient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlClient2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlClient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlClient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSent.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSent.setText("SENT");
        btnSent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSentMouseExited(evt);
            }
        });
        btnSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSentActionPerformed(evt);
            }
        });

        txtMess.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        pnlCard.setLayout(new java.awt.CardLayout());

        edChatBox1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        edChatBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        spClient1.setViewportView(edChatBox1);

        pnlCard.add(spClient1, "client1");

        edChatBox2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        spClient2.setViewportView(edChatBox2);

        pnlCard.add(spClient2, "client2");

        lblNameClient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNameClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameClient.setText("CLIENT 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMess, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSent))
                    .addComponent(lblNameClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCard, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSent, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(txtMess))
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SERVER CHAT BOX");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
// <editor-fold defaultstate="collapsed" desc="Sự kiện trên khung chat box">
    private void pnlClient1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClient1MouseEntered
        hover(pnlClient1, lblClient1, 0);
    }//GEN-LAST:event_pnlClient1MouseEntered

    private void pnlClient1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClient1MouseExited
        hover(pnlClient1, lblClient1, 1);
    }//GEN-LAST:event_pnlClient1MouseExited

    private void pnlClient2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClient2MouseEntered
        hover(pnlClient2, lblClient2, 0);
    }//GEN-LAST:event_pnlClient2MouseEntered

    private void pnlClient2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClient2MouseExited
        hover(pnlClient2, lblClient2, 1);
    }//GEN-LAST:event_pnlClient2MouseExited

    private void pnlClient1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClient1MouseClicked
        clickCard("client1");
        jPanel2.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_pnlClient1MouseClicked

    private void pnlClient2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClient2MouseClicked
        clickCard("client2");
        jPanel2.setBackground(Color.ORANGE);
    }//GEN-LAST:event_pnlClient2MouseClicked

    private void btnSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSentActionPerformed
        sentMess();
    }//GEN-LAST:event_btnSentActionPerformed

    private void btnSentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSentMouseExited
        // TODO add your handling code here:
        hover(btnSent, 1);
    }//GEN-LAST:event_btnSentMouseExited

    private void btnSentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSentMouseEntered
        // TODO add your handling code here:
        hover(btnSent, 0);
    }//GEN-LAST:event_btnSentMouseEntered
// </editor-fold>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSent;
    private javax.swing.JEditorPane edChatBox1;
    private javax.swing.JEditorPane edChatBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblClient1;
    private javax.swing.JLabel lblClient2;
    private javax.swing.JLabel lblNameClient;
    private javax.swing.JPanel pnlCard;
    private javax.swing.JPanel pnlClient1;
    private javax.swing.JPanel pnlClient2;
    private javax.swing.JScrollPane spClient1;
    private javax.swing.JScrollPane spClient2;
    private javax.swing.JLabel statusClient1;
    private javax.swing.JLabel statusClient4;
    private javax.swing.JTextField txtMess;
    // End of variables declaration//GEN-END:variables
// Method
// Phương thức hover thẻ clien
    private void hover(JPanel pnl, JLabel lbl, int i){
        if(i == 0){
            pnl.setBackground(new Color(51,51,51));
            lbl.setForeground(new Color(255,255,255));
        }else{
            pnl.setBackground(new Color(255,102,102));
            lbl.setForeground(new Color(51,51,51));
        }
    }
    
// Phương thức chuyển card
    private void clickCard(String name){
        lblNameClient.setText("CLIENT "+name.substring(6,name.length()));
    
    // Chuyển card    
        CardLayout card = (CardLayout) pnlCard.getLayout();
        card.show(pnlCard,name);  
    } 
    
// Gửi tin nhắn
    private void sentMess(){
        if(txtMess.getText().length() != 0){
            if(spClient1.isShowing()){
                messSocket.send("Bot tự động", txtMess.getText());
            }else if(spClient2.isShowing()){
                messSocket.send("Bot tự động", txtMess.getText());
            }
        }else JOptionPane.showMessageDialog(this, "Bạn chưa nhập tin nhắn!");
    }

// Phương thức kết nối
    private Thread connect(String name, JEditorPane edPane, int port){
        return new Thread(){
            public void run(){
                try {
                    serverSocket = new ServerSocket(port);
                    System.out.println("Waiting client connect.....");
                    socket = serverSocket.accept();
                    System.out.println("Server was connected by "+name);
                    messSocket = new ChatMesageSocket(socket,name,edPane);
                } catch (Exception e) {
                }
            }
        };
    }
    
// Phương thức hover chỉnh mày btn đơn 
    private void hover(JButton btn, int a){
        if(a == 0){
            btn.setBackground(new Color(51,51,51));
            btn.setForeground(new Color(204,204,204));
        }else{
            btn.setBackground(new Color(204,204,204));
            btn.setForeground(new Color(51,51,51));
        }
    }
}
